# Spring properties
spring:
  application:
     name: audio-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/audios-server/templates/    # Trailing / mandatory
                             # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server.port: 4444   # HTTP (Tomcat) port

# Enable actuator access without security checks - DEVELOPEMENT ONLY
management.security.enabled: true